### ISSUE TITLE
Unterkategorien für Listen, die nicht mit einfachen Konjunktionen verbunden sind?

### ISSUE THREAD

**Issue by behitz** [raykyn/BeNASch#18]
Listen bewähren sich für Bezüge und Attribute, die sich auf mehrere Personen beziehen. Nicht jedes dieser Bezüge lässt sich aber mit der jetztigen Listendefinition anwenden. Z.B. "Niclaus Rippel der Eltere contra Niclaus Sattler , beede von den Räthen". Aktuell lässt sich das nur über part-whole-Beziehungen lösen. Wäre es eine Option, zusätzliche Untertypen von Listen einzuführen à la LST_PAR für Parteien vor Gericht?

**Comment by raykyn** [comment]
Besprechung 20.07.2023:

Beschluss - Da es sich bei solchen Formulierungen um projektspezifische Probleme handelt, halten wir die Möglichkeit auf Unterkategorien von Listen erstmal als optionale Annotation fest, deren Nutzung in der Projektdokumentation festgehalten werden sollte, so dass etwaige andere Nutzer ungewünschte Listen entsprechend umwandeln können.
